development:
  adapter: postgresql
  database: das_board_development
  username: postgres
  password:
  host: localhost

test:
  adapter: postgresql
  database: das_board_test
  username: postgres
  password:
  host: localhost
