development:
  database: das_board_development
  port: 5984
  username: postgres
  password: postgres
  host: localhost

test:
  database: das_board_test
  port: 5984
  username: postgres
  password: postgres
  host: localhost
