development:
  adapter: postgresql
  database: das_board_development
  username: postgres
  password:
  host: localhost
  encoding: unicode
  pool: 5
  username: blancatortajada
  password:
  timeout: 5000
  port: 5432

test:
  adapter: postgresql
  database: das_board_test
  username: postgres
  password:
  host: localhost
  encoding: unicode
  pool: 5
  username: blancatortajada
  password:
  timeout: 5000
  port: 5432